### ISSUE TITLE
Blackout with complementary shader

### ISSUE THREAD

**Issue by iekiekkeikei** [aMelonRind/dark-sky#1]
Version 1.20.1-fabric 0.15.6

Loader fabric (and forge with connecter mod)

Mod
Dark sky
Iris Shaders
Sodium

Shader
Complementary Shader

Continuous darkening at sunrise and sunset.

I used a translation website. Sorry if there are any strange expressions.

**Comment by aMelonRind** [comment]
Fixed in 1.1.1 https://github.com/aMelonRind/dark-sky/commit/5b4babf498bd99202ea97f605210ee28a0e495d5

**Comment by iekiekkeikei** [comment]
Thank you!
